name: First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Repository Files
        run: ls -la

      - name: Print Working Directory
        run: pwd